import express from "express";
import controller from "./controller";
export default express
  .Router()
  .get("/", controller.getNFTs)
  .get("/most-liked", controller.getMostLiked)
  .get("/most-viewed", controller.getMostViewed)
  .get("/most-sold", controller.getMostSold)
  .get("/most-sold-series", controller.getMostSoldSeries)
  .get("/history", controller.getHistory)
  .get("/total-on-sale", controller.getTotalOnSale)
  .get("/total-filtered", controller.getTotalFiltered)
  .get("/:id", controller.getNFT)
  .get("/stat/:id", controller.getStatNFTsUser)
  .get("/series/data", controller.getNFTsBySeries)
  .get("/series/status/:seriesId", controller.getSeriesStatus)
  .get("/series/can-add", controller.canAddToSeries)
  .post("/like", controller.likeNft)
  .post("/unlike", controller.unlikeNft)
  .post("/add-nfts-categories", controller.addCategoriesNFTs)